[package]
name = "sha256-kimchi"
version = "0.1.0"
edition = "2021"

[dependencies]
kimchi = { git = "https://github.com/o1-labs/proof-systems", branch = "master" }
ark-ff = { version = "0.4.2", features = ["parallel", "asm"] }
ark-ec = "0.5.0"
num-bigint = "0.4.6"
sha2 = "0.10.8"
hex = "0.4"
